#define KAFKA_MAX_SUPPORTED_FETCH_REQUEST_API_VERSION 11
#define KAFKA_MAX_SUPPORTED_PRODUCE_REQUEST_API_VERSION 8

#define KAFKA_MIN_LENGTH (sizeof(kafka_header_t))
#define CLIENT_ID_SIZE_TO_VALIDATE 15
#define CLIENT_ID_MAX_STRING_SIZE 50
#define TOPIC_NAME_MAX_STRING_SIZE_TO_VALIDATE 48 // 16 * 3. Must be a factor of 16, otherwise a verifier issue can pop in kernel 4.14.
#define TOPIC_NAME_MAX_ALLOWED_SIZE 255

// The number of varint bytes required to support the specified values.
// 127
#define VARINT_BYTES_0000007f   1
// 16383
#define VARINT_BYTES_00003fff   2
// 2097151
#define VARINT_BYTES_001fffff   3
// 268435455
#define VARINT_BYTES_0fffffff   4

// Reasonable limit
#define VARINT_BYTES_NUM_TOPICS VARINT_BYTES_00003fff
// Limited by TOPIC_NAME_MAX_ALLOWED_SIZE
#define VARINT_BYTES_TOPIC_NAME_SIZE VARINT_BYTES_00003fff
// Reasonable limit
#define VARINT_BYTES_NUM_PARTITIONS VARINT_BYTES_00003fff
// Limited by KAFKA_MAX_ABORTED_TRANSACTIONS below
#define VARINT_BYTES_NUM_ABORTED_TRANSACTIONS VARINT_BYTES_00003fff
// Should ideally be as big as possible.
#define VARINT_BYTES_RECORD_BATCHES_NUM_BYTES VARINT_BYTES_0fffffff

#define TOPIC_NAME_MAX_STRING_SIZE 80

#define KAFKA_RESPONSE_PARSER_MAX_ITERATIONS 10

#define KAFKA_MAX_ABORTED_TRANSACTIONS 10000

#define KAFKA_BATCH_SIZE 14

#define KAFKA_TELEMETRY_TOPIC_NAME_NUM_OF_BUCKETS 10

#define KAFKA_TELEMETRY_TOPIC_NAME_BUCKET_SIZE 10