FROM ubuntu:22.04

RUN apt update && apt -y install libssl-dev dkms bc build-essential git make libelf-dev clang llvm strace tar bpfcc-tools gcc-multilib libbpf-dev linux-headers-generic flex bison

CMD ["sleep","infinity"]